# Generated by Django 3.0.4 on 2020-04-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyspider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('egg', models.CharField(max_length=2047)),
                ('settings', models.CharField(max_length=2047, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='template',
            name='path',
        ),
        migrations.AddField(
            model_name='job',
            name='args',
            field=models.CharField(max_length=2047, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='uuid',
            field=models.CharField(db_column='id', default=0, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='spider_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'FINISHED')], default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='site_templates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easyspider.SiteTemplates'),
            preserve_default=False,
        ),
    ]
