# Generated by Django 3.0.4 on 2020-05-01 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiderTemplate', '0002_auto_20200501_1325'),
        ('easyspider', '0002_auto_20200423_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='site_templates',
        ),
        migrations.AlterField(
            model_name='job',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyspider.Node'),
        ),
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spiderTemplate.Template'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SiteTemplates',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
