# Generated by Django 3.0.4 on 2020-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyspider', '0003_auto_20200501_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ready', '等待运行'), ('running', '正在运行'), ('paused', '暂停运行'), ('finished', '完成运行'), ('canceled', '已终止')], max_length=10),
        ),
    ]
