# Generated by Django 3.0.4 on 2020-05-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyspider', '0004_auto_20200501_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
