# Generated by Django 3.0.5 on 2020-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ready', '等待运行'), ('running', '正在运行'), ('paused', '已暂停'), ('finished', '已完成'), ('canceled', '已终止')], default='ready', max_length=10),
        ),
    ]
