# Generated by Django 3.0.5 on 2020-05-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTemplate', '0003_auto_20200501_2351'),
        ('task', '0002_auto_20200505_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spiderTemplate.Template'),
        ),
    ]
