# Generated by Django 3.0.5 on 2020-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200509_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='run_times',
            field=models.IntegerField(default=1),
        ),
    ]
