# Generated by Django 3.0.4 on 2020-05-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('_type', models.CharField(choices=[('life', '本地生活'), ('business', '电子商务'), ('reading', '媒体阅读'), ('search engine', '搜索引擎'), ('social', '社交平台'), ('education', '科研教育'), ('other', '其他')], db_column='type', max_length=255)),
                ('egg', models.CharField(max_length=2047)),
                ('settings', models.CharField(blank=True, max_length=2047, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('split_param', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField()),
                ('sample_data', models.TextField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderTemplate.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('input_label', models.CharField(choices=[('input', 'input'), ('textarea', 'textarea')], max_length=255)),
                ('input_type', models.ForeignKey(blank=True, null=True, on_delete=models.SET('text'), to='spiderTemplate.InputType')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderTemplate.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiderTemplate.Template')),
            ],
        ),
    ]
