# Generated by Django 3.0.4 on 2020-05-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTemplate', '0002_auto_20200501_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='input_label',
            field=models.CharField(choices=[('input', 'input'), ('textarea', 'textarea')], default='input', max_length=255),
        ),
        migrations.AlterField(
            model_name='param',
            name='input_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number')], default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='InputType',
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spiderTemplate.SiteType'),
        ),
    ]
