# Generated by Django 3.0.5 on 2020-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTemplate', '0003_auto_20200501_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='download_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='view_times',
            field=models.IntegerField(default=0),
        ),
    ]
