# Generated by Django 3.0.5 on 2020-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderTemplate', '0004_auto_20200510_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='length_limit',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='param',
            name='number_max',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='param',
            name='number_min',
            field=models.IntegerField(default=1),
        ),
    ]
