name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Write settings.py
      env:
        SETTINGS: ${{ secrets.SETTINGS }}
      run: echo "$SETTINGS" > EasySpiderWeb/settings.py
    - name: Run Tests
      run: |
        python manage.py test --noinput
