# Generated by Django 3.0.4 on 2020-05-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.CharField(db_column='id', max_length=50, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'RUNNING'), (3, 'FINISHED')], default=0)),
                ('args', models.CharField(max_length=4095, null=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.Node')),
            ],
        ),
    ]
